meta:
  environment: (( merge ))
  dns_root: (( merge ))
  security_groups: (( merge ))
  network_name: (( merge ))

  stemcell:
    name: bosh-aws-xen-ubuntu
    version: latest

jobs:
  - name: postgresql_leader_z1
    instances: 1
    networks:
      - name: postgresql1
  - name: postgresql_z1
    instances: 0
    networks:
      - name: postgresql1
    properties:
      postgresql:
        leader_address: (( "0.postgresql-leader-z1.postgresql1." meta.environment "." meta.dns_root ))

compilation:
  cloud_properties:
    instance_type: m1.small

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m1.small

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: postgresql1
    type: dynamic
    cloud_properties:
      security_groups: (( meta.security_groups ))
